[package]
name = "hexxd"
version = "0.1.0"
edition = "2021"
description = ""
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
regex = "1.5.4"
lazy_static = "1.4.0"
